### ISSUE TITLE
Vagrant SSH key fails

### ISSUE THREAD

**Issue by Vathasav** [coderefinery/automation#2]
Vagrant is trying to authenticate into virtual machine with SSH key and failing. Current vagrant configuration is not working for me on Mac. Works when I disable SSH key authentication by setting config.ssh.insert_key = false. 

In the Docker Vagrant file the vm is assigned a private ip "192.168.1.12 "and in the instructions it is written that notebook can be accessed at 127.0.0.1. When I try to spin up the coderefinery-docker vm, I get the following error  "coderefinery-docker: docker: Error response from daemon: Container command could not be invoked.."

**Comment by pkoskinen** [comment]
Issue was a bug in Vagrant version 1.8.5, more information in https://github.com/mitchellh/vagrant/issues/7610

Fix: update Vagrant to > 1.8.5
Confirmed to fix the issue in this case as well.
