### ISSUE TITLE
update vagrant configuration for docker-coderefinery 

### ISSUE THREAD

**Issue by Vathasav** [coderefinery/automation#4]
Set SELINUX to permissive
uncomment the private network ip
Good to remember - vagrant 1.8.5 fails with cent os 7 and virtual box 5.x (problem with vagrant --> update vagrant)
Mention few things about docker security issues.
For example: further reading - https://elastic-security.com/2016/04/11/docker-best-security-practices/

**Comment by pkoskinen** [comment]
Fixed Vagrant issue in https://github.com/coderefinery/tools/commit/26d42a6d24bd77b5c7e96e8fea23dcea4344b672

**Comment by pkoskinen** [comment]
Docker security issue marked with red font, https://github.com/coderefinery/automation/commit/b267bdb0d51a73b8ae14fa41a2e16120e3ff5c30
